name: build-app
on:
  push:
    branches:
    tags:
    paths_ignored:
      - ".github/workflows/updater.yml"
      - "updater/**"
      - "**.md"
  pull_request:
    paths_ignored:
      - ".github/workflows/updater.yml"
      - "updater/**"
      - "**.md"

jobs:
  build:

    name: build
    runs-on: ubuntu-latest

    steps:

      - name: set up go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: build and test
        run: |
          go test -v -race -timeout=100s -covermode=atomic -coverprofile=$GITHUB_WORKSPACE/profile.cov_tmp ./...
          go build -race ./...
          cat $GITHUB_WORKSPACE/profile.cov_tmp | grep -v "mocks" | grep -v "_mock" > $GITHUB_WORKSPACE/profile.cov

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64

      - name: install goveralls
        run: go install github.com/mattn/goveralls@latest

      - name: submit coverage
        run: $(go env GOPATH)/bin/goveralls -service="github" -coverprofile=$GITHUB_WORKSPACE/profile.cov
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

      - name: Set up QEMU
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Publish Docker Image
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: ghcr.io/w0rng/protolint-alignment:latest
